import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/auth";
import { aiEnabled } from "@/lib/ai";
import SupportChat from "@/components/SupportChat";

export const dynamic = "force-dynamic";

export default async function SupportPage() {
  const user = await getCurrentUser();
  if (!user) redirect("/login");

  return (
    <div className="mx-auto max-w-2xl space-y-4">
      <div>
        <h1 className="text-2xl font-bold">Support assistant</h1>
        <p className="text-sm text-neutral-600">
          {aiEnabled()
            ? "Answers are generated by an LLM using your order history."
            : "Running in offline mode — answers come from built-in rules and your order history."}
        </p>
      </div>
      <SupportChat />
    </div>
  );
}
